import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeModeScript, ThemeProvider } from "flowbite-react";
import "@/assets/css/globals.css";
import { mainTheme } from "@/lib/theme";
import ThemeToggler from "@/components/theme-toggler";
import Nav from "@/components/layouts/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: ReactNode;
}>;

export default async ({ children }: Props): Promise<ReactNode> => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} transition-colors`}
      >
        <ThemeProvider theme={mainTheme}>
          <Nav />
          {children}
          <ThemeToggler />
        </ThemeProvider>
      </body>
    </html>
  );
};
