import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FC } from "react";
import { ThemeModeScript, ThemeProvider } from "flowbite-react";
import "@/assets/css/globals.css";
import { mainTheme } from "@/lib/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<
  Readonly<{
    children: React.ReactNode;
  }>
> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={mainTheme}>{children}</ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
